# Generated by Django 3.2.7 on 2021-09-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='cat_relation',
        ),
        migrations.AddField(
            model_name='kit',
            name='cat_relation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
