# Generated by Django 3.2.7 on 2021-09-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210924_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='downvotes',
        ),
    ]
