# Generated by Django 3.2.7 on 2021-09-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_task_kit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='title',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='completed',
        ),
        migrations.AddField(
            model_name='kit',
            name='markdown_data',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='KitComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('comment', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.kit')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
