# Generated by Django 3.2.7 on 2021-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210907_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='profile_image',
            field=models.URLField(default=None),
        ),
    ]
