# Generated by Django 3.2.7 on 2021-09-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210904_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcomments',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
