# Generated by Django 3.2.7 on 2021-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kit_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='profile_image',
            field=models.URLField(default=None, null=True),
        ),
    ]
