# Generated by Django 3.2.7 on 2021-09-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_kit_downvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='categories',
            field=models.TextField(choices=[('Web Dev', 'Web Dev'), ('Graphic Design', 'Graphic Design'), ('Crypto', 'Crypto'), ('Data Science', 'Data Science'), ('Digital Marketing', 'Digital Marketing')], default='No Category'),
        ),
    ]
