# Generated by Django 3.2.7 on 2021-09-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_kit_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='categories',
            field=models.TextField(choices=[('Web Dev', 'Web Dev'), ('Graphic Design', 'Graphic Design'), ('Web 3', 'Web 3'), ('Data Science', 'Data Science'), ('Digital Marketing', 'Digital Marketing'), ('Startups', 'Startups'), ('Bootstrapping', 'Bootstrapping'), ('Writing', 'Writing')], default='No Category'),
        ),
    ]
