# Generated by Django 3.2.7 on 2021-09-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_kit_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='profile_image',
        ),
    ]
